### ISSUE TITLE
引用行の次の行も引用扱いとなる

### ISSUE THREAD

**Issue by zakk3456** [kasecato/vscode-backlog-wiki-preview#1]
引用した次の行が引用していなくても、
プレビュー画面では引用扱いとなってしまいます。

```
>あいうえお
かきくけこ
```
↓プレビューではこうなる
>あいうえお
>かきくけこ

↓が、Backlogではこうなる

> あいうえお

かきくけこ

## 環境
- Windows 8.1 Pro 64bit
- Visual Studio Code v1.24.1

**Comment by kasecato** [comment]
@zakk3456 ありがとうございます🙇 完全に再現しました🎉
本動作はプレビュー画面に使用している Markdown エンジン `markdown-it` の[仕様 2 breaks = paragraph](https://github.com/markdown-it/markdown-it/issues/211#issuecomment-191932958)ですが，少しだけ細工することで表示できそうです。少々お待ち下さい🙇

**Comment by kasecato** [comment]
@zakk3456 修正版 [v0.0.5](https://marketplace.visualstudio.com/items?itemName=k--kato.vscode-backlog-wiki-preview) をリリースしました🙇 ご確認をどうぞよろしくおねがいします🙇

**Comment by zakk3456** [comment]
@kasecato 修正内容を確認しました！
お早い対応ありがとうございましたm(__)m
